server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8719
  zipkin:
    base-url: http://127.0.0.1:9411
    sender:
      type: web
    discovery-client-enabled: true
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://localhost:9200
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.24.114
    virtual-host: muzzly
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1 # 能者多劳
        acknowledge-mode: manual
        concurrency: 3 # 避免消息堆积，初始化多个消费者线程
      type: simple # simple-listener容器使用一个额外线程处理消息  direct-listener（监听器）容器直接使用consumer线程
feign:
  sentinel:
    enabled: true

